# Generated by Django 5.2.7 on 2025-10-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('profile_image', models.ImageField(upload_to='', verbose_name='patient_image/')),
                ('visit_nums', models.IntegerField(default=1)),
                ('recent_visit', models.DateField(auto_now_add=True)),
                ('severity_percentage', models.IntegerField()),
                ('status', models.CharField(choices=[('MR', 'MODERATE_RISK'), ('LR', 'LOW_RISK'), ('HR', 'HIGH_RISK')], db_index=True, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
