# Generated by Django 5.2.7 on 2025-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_recent_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='severity_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('MR', 'MODERATE_RISK'), ('LR', 'LOW_RISK'), ('HR', 'HIGH_RISK')], default='LR', max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Patient_Image',
        ),
    ]
