# Generated by Django 5.2.7 on 2025-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_severity_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(upload_to='patient_image/'),
        ),
    ]
