# Generated by Django 5.2.7 on 2025-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_severity_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='severity_percentage',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
