# Generated by Django 4.1.13 on 2025-10-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_probability', models.IntegerField()),
                ('result', models.CharField(max_length=255)),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sytmptom', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('MR', 'MODERATE_RISK'), ('LR', 'LOW_RISK'), ('HR', 'HIGH_RISK')], max_length=2)),
                ('doctor_diagnosis', models.CharField(max_length=255, null=True)),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ai_diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkups', to='diagnose.ai_diagnosis')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OCT_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patient_oct_images/')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('checkup_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oct_image', to='diagnose.checkups')),
            ],
        ),
    ]
