# Generated by Django 4.1.13 on 2025-10-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkups',
            name='sytmptom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
