# Generated by Django 4.1.13 on 2025-10-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('diagnose', '0002_alter_checkups_sytmptom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AI_Diagnosis',
            new_name='AI_Diagnose',
        ),
        migrations.RenameModel(
            old_name='Checkups',
            new_name='Checkup',
        ),
    ]
