# Generated by Django 4.1.13 on 2025-10-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0004_rename_ai_diagnose_ai_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='sytmptom',
        ),
        migrations.AddField(
            model_name='checkup',
            name='symptom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ai_diagnosis',
            name='ai_probability',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ai_diagnosis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='ai_diagnosis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkup', to='diagnose.ai_diagnosis'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oct_image',
            name='checkup_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oct_images', to='diagnose.checkup'),
        ),
        migrations.AlterField(
            model_name='oct_image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
