# Generated by Django 5.2.7 on 2025-10-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0005_rename_patient_id_checkup_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='ai_diagnosis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkup', to='diagnose.ai_diagnosis'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='doctor_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='status',
            field=models.CharField(blank=True, choices=[('MR', 'MODERATE_RISK'), ('LR', 'LOW_RISK'), ('HR', 'HIGH_RISK')], max_length=2, null=True),
        ),
    ]
