# Generated by Django 5.2.7 on 2025-10-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0006_alter_checkup_ai_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='ai_diagnosis',
        ),
        migrations.RemoveField(
            model_name='oct_image',
            name='checkup_id',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='doctor_diagnosis',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='status',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='symptom',
        ),
        migrations.CreateModel(
            name='DiagnosisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DR', 'DOCTOR'), ('AI', 'AI'), ('RV', 'REVIEW')], db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('MR', 'MODERATE_RISK'), ('LR', 'LOW_RISK'), ('HR', 'HIGH_RISK')], db_index=True, max_length=2)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('classification', models.TextField(blank=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='diagnose.checkup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCTImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='patient_oct_images/')),
                ('checkup_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oct_images', to='diagnose.checkup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AI_Diagnosis',
        ),
        migrations.DeleteModel(
            name='OCT_Image',
        ),
    ]
