version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Docker/BackEnd/Dockerfile
    image: aeye_ai_back:1.0
    ports:
    - "8000:8000"
    volumes:
    - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    
  ai:
    build:
      context: ..
      dockerfile: Docker/AI/Dockerfile
    image: aeye_ai:1.0
    ports:
    - "8888:8888"
    volumes:
    - .:/app
    
