# Generated by Django 5.2.7 on 2025-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(upload_to='user_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
