type: develop

FASTAPI:
  HOST : localhost
  PORT : 8000
  API_PREFIX : /api/v1
  WORKERS : 1
  RELOAD : True
  LOG_LEVEL : info

Vision_AI:
  network: vgg16
  pretrained: True
  checkpoint: ./best_validation_weights.pt
  input_size: 224
  in_channels: 3
  num_classes: 7
  criterion: cross_entropy


HTTP:
  BATCH_THRESHOLD : 256
  BATCH_TIMEOUT : 1.0 # 1sec
