# Generated by Django 5.2.7 on 2025-10-11 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnose', '0007_remove_checkup_ai_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=10)),
                ('model_weight', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=10)),
                ('ai_probability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_version', to='diagnose.diagnosisinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
