#############################################################
# AEYE Web Docker Compose File
# Created By Yoonchul Chung
# Created At 2024.08.03
# Welcome to Visit Github : https://github.com/Yoonchulchung
#############################################################
version: '3.3'

services:
  frontend:
    build:
      context: ..
      dockerfile: Docker/Front/Dockerfile
    image: aeye_web_front:1.0
    container_name:  aeye_web_front
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npm start"
    networks:
      - aeye_web
  backend:
      build:
        context: ..
        dockerfile: Docker/Backend/Dockerfile
      image: aeye_web_backend:1.0
      container_name:  aeye_web_backend
      ports:
        - "8000:8000"
      command: sh -c "npm run build && npm start"
      networks:
        - aeye_web
networks:
  aeye_web:
    driver: bridge