# Generated by Django 5.2.7 on 2025-10-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckupMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eye_side', models.CharField(choices=[('L', 'LEFT'), ('R', 'RIGHT')], db_index=True, max_length=1)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='diagnosis.checkup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DR', 'DOCTOR'), ('AI', 'AI'), ('RV', 'REVIEW')], db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('MR', 'MODERATE_RISK'), ('LR', 'LOW_RISK'), ('HR', 'HIGH_RISK')], db_index=True, max_length=2)),
                ('classification', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=2048)),
                ('result_summary', models.CharField(blank=True, max_length=2048)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='diagnosis.checkup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCTImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oct_img', models.ImageField(upload_to='patient_oct_images/')),
                ('checkup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oct_images', to='diagnosis.checkup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
