# Generated by Django 5.2.7 on 2025-10-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosis_date_alter_octimage_checkup'),
        ('patient', '0002_alter_patient_severity_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='patient.patient'),
        ),
    ]
