# Generated by Django 4.1.13 on 2025-10-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0003_rename_ai_diagnosis_ai_diagnose_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AI_Diagnose',
            new_name='AI_Diagnosis',
        ),
    ]
