"""reuslt_summary val updated

Revision ID: 5c9d77e52516
Revises: bda2b23781fd
Create Date: 2025-10-20 03:07:58.762621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c9d77e52516'
down_revision: Union[str, None] = 'bda2b23781fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Result', 'result_summary',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Result', 'result_summary',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
