"""add request table

Revision ID: bda2b23781fd
Revises: c278d067175b
Create Date: 2025-10-20 02:43:52.408785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bda2b23781fd'
down_revision: Union[str, None] = 'c278d067175b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img_path', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=2048), nullable=False),
    sa.Column('result_summary', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.drop_index('job_id', table_name='InferenceResult')
    op.drop_table('InferenceResult')
    op.drop_table('Image')
    op.drop_index('email', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'User', ['email'], unique=True)
    op.create_table('Image',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img_path', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('InferenceResult',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('result', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('classification', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('job_id', 'InferenceResult', ['job_id'], unique=True)
    op.drop_table('Result')
    op.drop_table('Request')
    # ### end Alembic commands ###
