"""add Inference Table

Revision ID: c278d067175b
Revises: 3125142c03fb
Create Date: 2025-10-18 17:20:46.296378

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c278d067175b'
down_revision: Union[str, None] = '3125142c03fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('InferenceResult', 'job_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('InferenceResult', 'job_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
