"""add Inference Table

Revision ID: 3125142c03fb
Revises: 9144f3e04467
Create Date: 2025-10-18 17:19:37.727220

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3125142c03fb'
down_revision: Union[str, None] = '9144f3e04467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('InferenceResult', 'result',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('InferenceResult', 'result',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
