version: '3.3'

services:
  AEYE-OpticNet:
    image: aeye_opticnet:1.0
    container_name: opticnet_container
    build:
      context: ..
      dockerfile: Docker/AEYE_AI/Dockerfile
    ports:
    - "2000:2000"
    - "6006:6006"
    - "8888:8888"
    volumes:
    - /home/:/home/
    environment:
        - PYTHONPATH=/app/
    networks:
      - ai_network
    command: python manage.py

networks:
  ai_network:
    driver: bridge
