# Generated by Django 3.2 on 2024-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeye_inference_models',
            name='message',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='aeye_inference_models',
            name='whoami',
            field=models.CharField(max_length=40),
        ),
    ]
