# Generated by Django 3.2 on 2024-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0002_auto_20240809_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeye_database_read_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoami', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=40)),
                ('request_data', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='aeye_database_write_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoami', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=40)),
                ('request_data', models.CharField(max_length=40)),
            ],
        ),
    ]
